insert into TIPOHABITACION (ID, TIPO, DESCRIPCION, PRECIO, CAPACIDAD) values (1, 'SUITE', 'UNA HABITACION LINDA', 1000, 5);
insert into TIPOHABITACION (ID, TIPO, DESCRIPCION, PRECIO, CAPACIDAD) values (2, 'SUITE', 'UNA HABITACION LINDA', 2000, 10);
insert into TIPOHABITACION (ID, TIPO, DESCRIPCION, PRECIO, CAPACIDAD) values (3, 'ESTANDAR', 'UNA HABITACION NORMAL', 500, 5);
insert into TIPOHABITACION (ID, TIPO, DESCRIPCION, PRECIO, CAPACIDAD) values (4, 'ESTANDAR', 'UNA HABITACION NORMAL', 1000, 10);



